### PR TITLE
Add support for IT8688 and Z390 M gaming

### PR DESCRIPTION
**Pull request by crevetor**

### CODE REVIEW

**Comment by BadlyAnticipated** [comment]
Only adding the changes from:
Add IT8688E chip type
Add support for IT8688E in IT87XX.cs

Works like a charm for my Gigabyte Z390 Aorus Ultra IT8688E chip nicely. Thank you.

Now I just need support for the IT8792E chip.

**Comment by BadlyAnticipated** [comment]
If you would be so kind, show me what I need to change to make it work.

The IT8972E is a second chip on the board. Hope OHW can read 2 chips at the same time.

**Comment by crevetor** [comment]
I would need the model of your motherboard as it appears in OHM.

**Comment by BadlyAnticipated** [comment]
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2730729/OpenHardwareMonitor.Report.txt)

Assume this has the info you need ?

**Comment by fbattle** [comment]
[OpenHardwareMonitor.Report.Z390-UD.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2730764/OpenHardwareMonitor.Report.Z390-UD.txt)

Here's the OHM report for the Z390 UD.  I hope it helps.

**Comment by crevetor** [comment]
I added support based on the reports you sent. Can you guys try it out ?

**Comment by crevetor** [comment]
FYI, the way I checked if it was correct was running the gigabyte SIV utility while running OHM and checking that the temps and voltages match.

**Comment by fbattle** [comment]
My friend reports the latest changes work. He ran the same Gigabyte utility to confirm the voltages and temps.

**Comment by BadlyAnticipated** [comment]
Works like a charm for my IT8688E chip ... would love to see that 8792 support as my other 3 fans are connected to that chip.

**Comment by crevetor** [comment]
@sushi1992 what motherboard is it on ?

**Comment by sushi1992** [comment]
@crevetor when I do a check on the board it simply comes back as Lenovo (model is invalid). It's a Lenovo Y500, about 5/6 years old :(.

**Comment by crevetor** [comment]
Do you have a utility to check your fans/temperatures ?

**Comment by sushi1992** [comment]
That's the problem, I wanted to check fans but no utility works. I coded something using WMI to get CPU temp, but win32_fan had empty fan speed. Speedfan cannot detect it either - comes back as 0. Hence trying to go about this way as I really want to get hold of the fan speeds. Couldn't find the datasheet for IT8580E but that's what's in the failure log of this app when I run it.

**Comment by crevetor** [comment]
Ok, that's unfortunate. If you had an app that is able to read the fan speeds you could just reverse engineer it.

**Comment by sushi1992** [comment]
I know :(... Sadly nothing is able to read it. Can only hope somehow someone knows what byte to read in order to get the correct information for it... Though I doubt that'll ever be possible without the datasheet...

**Comment by Phyxion** [comment]
@crevetor Feel free to submit this PR also to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/ so it can actually be merged.

**Comment by moellerm** [comment]
The 10th and 11th voltage would be read from the same register as the first and second temperature sensor, that is from 0x29 and 0x2A. That means the 11 voltage sensors can't be right. I have reduced kept 9 voltage sensors for the IT8688E and committed the changes. Unfortunately, I do not have any datasheet for IT8688E, so I can't really verify.

I have also some experimental fan control (software mode) based on IT8721F, but there is some unexpected behavior. So unless someone with access to the datasheet can help out, I think it is best to not include software fan control.

@crevetor can you update the pull request with your mainboard profiles using 9 voltage sensors only, and remove the commits for the IT8688E support (included already)?

**Comment by crevetor** [comment]
@moellerm PR updated. Be warned that I haven't built and tested this code though.

**Comment by moellerm** [comment]
I have merged the changes (with a small fix for the mainboard configurations commit). The IT8688E should go into GetITEConfigurationsB because the code is based on the IT8721F and the default configurations in GetITEConfigurationsB (for unknown mainboards) should better match the actual situation. And I think you missed `case Chip.IT8688E:` line in your commit.

Thank you for your contribution.

**Pull request closed without merging**
