### PR TITLE
for a little Ryzen support

### PR DESCRIPTION
**Pull request by rmattuschka**
this can help for Issue #961 #957 ...

### CODE REVIEW

**Comment by DarthDestroyer** [comment]
Is that a Mistake, that the pull is closed?

**Comment by sebastian-dev** [comment]
I working currently on a full ryzen, threadripper and epic support.
Temperature readings are fine.
Clock and Power informations need some time. ;)

**Comment by aquacomputer** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/17
The Ryzen support is online

**Comment by moellerm** [comment]
Ryzen support should be implemented in commit https://github.com/openhardwaremonitor/openhardwaremonitor/commit/97b03945ae9ec39e11023cfd14b712fb949f908f

**Pull request closed without merging**
