### PR TITLE
Display both " Celsius and Fahrenheit" in the TreeView

### PR DESCRIPTION
**Pull request by rmattuschka**
to display temperatures like "40*C (104*F)" under temperaturunit fahrenheit.
but only in the treeview.

it's  a sample for #971

### CODE REVIEW

**Comment by DarthDestroyer** [comment]
I am commenting this, because that this pull will make some trouble. That is the reason, why i wouldnt do / accept that so. 
Without an option / switch to toggle this, the Fahrenheit Guys will cry and they dont want it - if you change the Celsius Part, these guys will cry...

A New Temp-format named "both" would be the best Solution, i think!

Thanks anyway! Regards

**Comment by rmattuschka** [comment]
This is a suggestion!
Can anyone do as he wants.

**Comment by DarthDestroyer** [comment]
Yep... And i extend it ;)

**Comment by rmattuschka** [comment]
Make it better! less blaaa blaaa

**Comment by DarthDestroyer** [comment]
I dont get, why you have to complain about a Suggestion... 

btw, it wasnt a personal attack! It was a tipp to get YOUR PR accepted... 
For me,  it doesnt matter anyways!

Nice Weekend!

**Comment by moellerm** [comment]
As mentioned already, we need to keep the Celsius only and Fahrenheit only options. One might, implement a "both" option as well, but this pull request does not really provide that.

**Pull request closed without merging**
