### PR TITLE
Implement Nuvoton NCT6102D/NCT6106D chips.

### PR DESCRIPTION
**Pull request by deveee**
Hi,

Based on this documentation:
https://www.nuvoton.com/resource-files/NCT6102D_NCT6106D_Datasheet_V1_0.pdf
I implemented NCT6102D/NCT6106D chips.

Basically everything should work fine. Fans values and temperatures are ok. I can't really say what about voltages because it's hard to determine how big values I should get. But I get something about 1-3 V.

Regards,
Deve

### CODE REVIEW

**Comment by deveee** [comment]
It's been one week since I prepared this pull request and I didn't receive any answer. Are you interested in it at all? Should I explain or correct something?

Regards,
Deve

**Comment by moellerm** [comment]
Thank you for this, I'm interested in merging it. I haven't completely reviewed the details of your implementation and I haven't looked at the documentation yet.

There are currently two (small) obstacles that prevented from merging directly. 

First I need to familiarize me with Git a bit more in order not to make a mess (I'm really familiar with SVN and Mercurial only). Moving things here from the (now closed) Google Code SVN repository was kind of a last minute action.

Second I think I should factor out a common abstract base class for NCT610X and NCT677X in order to reduce the duplication of code. First I thought about integrating it into NCT677X, but there might be just too many differences. So an abstract base class might be the best choice.

**Comment by moellerm** [comment]
Sorry it took so long, but I finally managed to look into this.

It would be great if you could test the latest commit to check if it still runs the way it should on that chip.

**Comment by deveee** [comment]
Thanks!

Currently we are using different motherboard (in the previous one we burned
LVDS connector due to a wrong cable). But I will check it when we have this
motherboard in use again.

**Comment by deveee** [comment]
I finally have access to the motherboard with this chip. I just tested OpenHardwareMonitor 0.8.0 and it works fine.

**Pull request merged**
