### PR TITLE
Support for Intel's 11th gen Rocket Lake.

### PR DESCRIPTION
**Pull request by Cereal-Killa**
Tested here and reads the temps fine on my i7 11700.

rfm9bSxoSN

### CODE REVIEW

**Comment by eulers-secret** [comment]
I also tested this PR on an i7-11700K and found it functional, including the web interface.

LGTM!

**Comment by pgrawehr** [comment]
Since maintenance on this repo unfortunately is a bit low, I have started merging a few of the open PRs here into a fork. There's a new build available that includes these changes [here](https://github.com/hexagon-oss/openhardwaremonitor/releases/tag/v0.9.7-alpha01). Feel free to retarget the PR to that fork or create a new issue if things are not working as expected.

**Comment by briankelly** [comment]
+1 from me. Looks good on my i5-11600K. Screenshot below shows a long Cinebench session running on my i5-11600K clocked to 5.0 GHz (using Intel Performance Maximizer).

Thanks for adding Rocket Lake support.

OHM running branch with support for i5-11600K 2021-06-03

**Comment by Cereal-Killa** [comment]
> Since maintenance on this repo unfortunately is a bit low, I have started merging a few of the open PRs here into a fork. There's a new build available that includes these changes [here](https://github.com/hexagon-oss/openhardwaremonitor/releases/tag/v0.9.7-alpha01). Feel free to retarget the PR to that fork or create a new issue if things are not working as expected.

The build on that fork works perfectly, thanks.

**Comment by briankelly** [comment]
Hey @pgrawehr, I tried your [v0.9.7-alpha01](https://github.com/hexagon-oss/openhardwaremonitor/releases/tag/v0.9.7-alpha01) and the x and y axis labels were missing from my charts. Screenshot below. 

I would've opened an issue on your forked repo, but there it looks like Issues are disabled on your repo.

image

**Comment by pgrawehr** [comment]
@briankelly I have enabled issues now. Please do create an issue. This is likely a regression due to me upgrading the oxyplot library. The one previously boundled with OHM was very old (and not a nuget-package).

**Comment by Cereal-Killa** [comment]
> @briankelly I have enabled issues now. Please do create an issue. This is likely a regression due to me upgrading the oxyplot library. The one previously boundled with OHM was very old (and not a nuget-package).

https://github.com/hexagon-oss/openhardwaremonitor/pull/3

**Comment by Tyux** [comment]
Thanks, it's worked for my 11700K!

**Comment by Cereal-Killa** [comment]
https://github.com/Cereal-Killa/openhardwaremonitor/releases/tag/0.10.0-alpha1

**Pull request closed without merging**
