### PR TITLE
Compiling of fan control pull request and latest build

### PR DESCRIPTION
**Pull request by Openuser81**
Would anyone be kind enough to merge and compile the latest Libre build with an older request to control fans via custom-made curves (https://github.com/openhardwaremonitor/openhardwaremonitor/pull/996)?  I've been trying but keep getting many errors and I can't figure out what the problem is.

Thanks.

### CODE REVIEW

**Comment by DarthDestroyer** [comment]
i dont think, that the libre changes will be accepted 1to1!

Why are you not opening an issue with the libre guys and ask there to implement that?

**Comment by Openuser81** [comment]
I tried to and it put it here.  I'm sorry, I'm not very savvy at GitHub.

**Comment by DarthDestroyer** [comment]
No Probem! ;)

I would recommend to ask here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

And the Error means, that you have to edit some files, that everything will work!

**Comment by Openuser81** [comment]
That's where I tried to ask.  When I click on Pull Request, it sends me here :-/

**Comment by SorceressEpele** [comment]
I forked it into a personal repository at https://github.com/SorceressEpele/LibreHardwareMonitor
It's a little bit out-of-date though.

**Comment by pawg** [comment]
Thanks @SorceressEpele, you've made my day.

I've made a request in LibreHardwareMonitor's Issues, your fork should really be merged in master : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/169

**Pull request closed without merging**
